### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by konjoinfinity** [DevMaster95/coin-promoting#1]
Is this a test application or will it be pushed to production (mainnet)?

**Comment by DevMaster95** [comment]
This project is in the progress in testing

**Comment by DevMaster95** [comment]
can you help me with this project?

**Comment by Magnitude0** [comment]
what are we doing here exactly?

**Comment by DevMaster95** [comment]
Hello, how are you today?
We are looking for a senior front-end developer to complete our coin-promoting project.
Due to some problems, our prior developer can't work anymore on our project right now.
So we want you to contact us to help with the frontend part in tech and development.
we have to build the other parts and need to integrate it into the main project.
But everything will start with the initial project.
So we want you to check our initial project first and understand all things on the current project exactly before starting work.
If everything is going well, we will have the tech meeting and will provide all the details.
After checking, let us know if the initial project is working well on your side.
Thank you.

**Comment by asqarbekolimov** [comment]
> Hello, how are you today? We are looking for a senior front-end developer to complete our coin-promoting project. Due to some problems, our prior developer can't work anymore on our project right now. So we want you to contact us to help with the frontend part in tech and development. we have to build the other parts and need to integrate it into the main project. But everything will start with the initial project. So we want you to check our initial project first and understand all things on the current project exactly before starting work. If everything is going well, we will have the tech meeting and will provide all the details. After checking, let us know if the initial project is working well on your side. Thank you.

Please, contact me info@asqarbekdev.uz . I am freelancer at Fiverr.

**Comment by DevMaster95** [comment]
Hello, thanks for your contacting.
I want to communicate on telegram.
My id is orcaurion1.

**Comment by asqarbekolimov** [comment]
> Hello, thanks for your contacting. I want to communicate on telegram. My id is orcaurion1.

I wrote to you by telegram

**Comment by SpasiboKojima** [comment]
Do not run anything authored by this person
[server/test/index.js](https://github.com/DevMaster95/coin-promoting/blob/6871ec488a0e76f5bb59c384af70f2976b943f02/server/test/index.js#L133)
